- edgeapplications.yaml
**WHAT**
Add missing fields to rules engine
**WHAT**
[NO ISSUE]
> fix[rules engine]: add target field to patch and put

- services.yaml
**WHAT**
Change `type` to `trigger`, so we send and receive the same data.
**WHY**
[ENG-19923]
[ENG-19923]: https://aziontech.atlassian.net/browse/ENG-19923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-19923] chore: (resources) change type to trigger

- idns.yaml
Separating methods:
* RecordPostOrPut
* RecordGet
Adding field weight to Record
> Adding field weighted to record

- .github/workflows/generate.yml
- credentials.yaml
- edgenode.yaml
**WHAT**
- Change java version to 11;
- Add python and javascript automatic SDK generation.
> test: python and javascript SDK generation

- storageapi.yaml
> feat: add storageapi

- credentials.yaml
- domains.yaml
- edgeapplications.yaml
- edgefunctions.yaml
- edgenode.yaml
- idns.yaml
- services.yaml
- storageapi.yaml
**WHAT**
- Update security schema to `tokenAuth`.
> chore: update security schema

- variables.yaml
> feat: add variables

- edgeapplications.yaml
fixing response for edge Applications get All
Adjusting interface object
> fix: adjusting edge application for get All

- networklist.yaml
This adds missing properties to Network Lists' schema.
> [NO-ISSUE] fix: Correct Network Lists' schema structure

- edgeapplications.yaml
Change debug_rules for boolean
> fix: adjusting edge application for debug_rules boolean

- domains.yaml
**WHAT**
- Domains list was missing query params
> chore: add queries to domains list

- variables.yaml
These changes also improve tests using [schemathesis tool](https://schemathesis.readthedocs.io/en/stable/)
> fix: adjusts to run properly on python SDK

- .github/workflows/ci.yml
- credentials.yaml
**WHAT**
- Add openapi-linter to workflow - PR will now show an error when linter fails.
> feat: add openapi-linter

- storageapi.yaml
**WHAT**
- Update to latest yaml
- SDK tested locally
> chore: update storage-api yaml

- .github/workflows/ci.yml
- edgeapplications.yaml
- storageapi.yaml
Our second linter is not blocking failing OpenAPI definitions, this PR fixes it 😃 ;
Fix edge-application indentation;
> fix: redocly linter

- .github/workflows/generate.yml
- edgeapplications.yaml
**WHAT**
- Change node to 18 to test if SDK generation works;
> chore: change node to 18

- .github/workflows/generate.yml
- storageapi.yaml
**WHAT**
- Add .gitignore back to script;
- Add storageapi.yaml for complete generation;
> chore: add .gitignore back to script

- edgeapplications.yaml
**WHAT**
- Add required fields to edgeapplications yaml;
> chore: add required fields to edgeapplication yml

- networklist.yaml
https://github.com/aziontech/schemathesis-tests/actions/runs/5467559661/jobs/9954027237
> fix: OpenAPI specs networklist.yaml

- variables.yaml
https://github.com/aziontech/schemathesis-tests/actions/runs/5487728283/jobs/9999581955#step:6:31
- Update servers URL from https://stage-variables.azion.com to https://stage-api.azion.net/variables
- Update endpoints from /api/variables to /variables
> fix: specs variables.yaml

- edgeapplications.yaml
**WHAT**
- Add description field to rules engine requests and response;
> chore: add description field to rules engine

- data_streaming.yml
[QA-881 - [openAPI] List all data streamings](https://aziontech.atlassian.net/browse/QA-881)
[QA-889- [openAPI] List all domains to use on data streaming](https://aziontech.atlassian.net/browse/QA-889)
[QA-890- [openAPI] Retrieve data streaming by ID](https://aziontech.atlassian.net/browse/QA-890)
[QA-891- [openAPI] List data streaming's templates](https://aziontech.atlassian.net/browse/QA-891)
[QA-892- [openAPI] Retrieve data streaming's template by ID](https://aziontech.atlassian.net/browse/QA-892)
> [QA-848] feat: Get methods for data streaming API

- edgeapplications.yaml
Fix: Cache Settings Request/Response PUT
> [ENG-26559] Fix: cache settings put

- edgefunctions.yaml
https://github.com/aziontech/azionapi-openapi/actions/runs/5696129861/job/15440628974
> fix: edge functions nullable options previous next and 404

- networklist.yaml
[[ENG-26778] ](https://aziontech.atlassian.net/browse/ENG-26778)
[ENG-26778]: https://aziontech.atlassian.net/browse/ENG-26778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-26778] feat:  update POST, GET and GET in networklist.yaml

- edgeapplications.yaml
chore: Updated contract, added websocket param in edge_app:
- GET edge_applications/<:id>
- POST edge_applications
- PATCH edge_applications/<:id>
- PUT edge_applications/<:id>
> [ENG-26941] chore: Updated contract, added websocket param in edge_app

- .github/workflows/generate.yml
**WHAT**
- Update generator name (`csharp-netcore` -> `csharp`)
> chore: update generator name

- data_streaming.yaml
This is a test of the new SDK generation method
> new response

- edgefirewall.yaml
fix: Added 404 in ruleset to put, patch and delete
[ENG-27003]: https://aziontech.atlassian.net/browse/ENG-27003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-27641] fix: Added 404 in ruleset to put, patch and delete

- edgefirewall.yaml
[ENG-27003]: https://aziontech.atlassian.net/browse/ENG-27003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-27003] fix: Added pagination and especific args

- .github/workflows/generate.yml
- edgefunctions.yaml
Add action to create a merged.yaml to be used by ChatGPT plugin.
> ci: action to create merged.yaml for ChatGPT plugin.

- iam.yml
adding iam schema for openapi v3
I have read the CLA Document and I hereby sign the CLA
> chore: adding iam schema

- edgeapplications.yaml
[ENG-27362]
[ENG-27362]: https://aziontech.atlassian.net/browse/ENG-27362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-27362] fix: remove caching attr from put methods

- edge.yml
Auto-generated Schema for Edge
> Auto-generated Schema for Edge

- domains.yaml
Add missing and fixes incorrect fields in the response and request schemas.
> fix: domains endpoint - missing and incorrect fields
